### ISSUE TITLE
Detach all events

### ISSUE THREAD

**Issue by dsivachenko** [bcerati/event-bus-js#1]
Hello! Thank you for this plugin! Is possible to detach all events? This would be in demand when writing unit tests.

**Comment by FrankV01** [comment]
Just recreate the event bus object....

**Comment by bcerati** [comment]
Yes you can just recreate the event bus object. But you're right it can be usefull. You can now detach all the callbacks for a given name or detach all the events in the bus:

```js
bus.detach('my-event');

// or

bus.detachAll();
```

Released in 0.0.4: https://www.npmjs.com/package/js-event-bus/v/0.0.4
