### ISSUE TITLE
in emit，name is own properties in window

### ISSUE THREAD

**Issue by hezhengjie** [bcerati/event-bus-js#10]
in emit function，use name to traverse listeners，but name is own properties in window，so if i don't compression
the code，we will can‘t correctly emit event

![image](https://user-images.githubusercontent.com/11374813/128827155-21124ea2-daa1-4060-bc56-4f0620cff98b.png)

**Comment by bcerati** [comment]
Oh yes, you're right!

I don't know why I have not written "for (var name ...)" instead.

It's fixed and published in a 1.1.1 version.

Thanks.
