### ISSUE TITLE
can't pass event data

### ISSUE THREAD

**Issue by FrankV01** [bcerati/event-bus-js#2]
I was trying to use the lib but it seems that I can't pass any data to event handlers. I.E. 

```
eventBus.emit('my-event', {myAwesome:'Data'});
````

Consumed in the following manner: 

```
eventBus.on('my-event', function(arg1) { console.log('my-event emitted', arg1) }); 
```

To me, this is a pretty important feature...

**Comment by bcerati** [comment]
@FrankV01 Yes you're right it is an important feature. But you can already do what you want :)

I updated the doc to add the way we can emit the event.

The second argument is the context of execution (you can pass `null` or `undefined` if you want). Here is the prototype of the emit function:

```js
emit(eventName, context, ...args)
```

So in your example:

```js
eventBus.emit('my-event', null, {myAwesome:'Data'});
```
