### ISSUE TITLE
detach event all callback bug

### ISSUE THREAD

**Issue by hnsylitao** [bcerati/event-bus-js#7]
https://github.com/bcerati/js-event-bus/blob/master/src/index.js#L115-L125

When there are 3 callbacks only 2 removed

**Comment by bcerati** [comment]
Thank you for your issue.

It has been resolved and released as a v1.0.2 version.

https://github.com/bcerati/js-event-bus/commit/090ccbb68141778f9fed0b7c5ad25f4f276c7c90
