### ISSUE TITLE
CDN Link ?

### ISSUE THREAD

**Issue by nicolasgoudard** [bcerati/event-bus-js#8]
Hello, Is there a CDN link for this library ?
thanks in advance
greetings

**Comment by bcerati** [comment]
Hello @nicolasgoudard, you can use jsdeliver ? https://cdn.jsdelivr.net/npm/js-event-bus@1.0.3/lib/js-event-bus.min.js

**Comment by nicolasgoudard** [comment]
thanks ! I will use it and I hope this project will be maintained.
I see another project, EventEmitter3 but I think js-event-bus is  written more cleanly

**Comment by bcerati** [comment]
@nicolasgoudard tahnk you :)

Yes it'll be maintained. I'll be adding some tests in the next few weeks to ensure there will be no breaking changes in the future releases.
